### ISSUE TITLE
Support hyphenation on Windows

### ISSUE THREAD

**Issue by dkager** [snaekobbi/pipeline-mod-dedicon#25]
libhyphen-native isn't available. Are there alternatives?

**Comment by bertfrees** [comment]
I've basically been deferring this issue because we haven't looked at full Windows support until now. The idea is to compile libhyphen for Windows, I just haven't succeeded in that yet. Haven't tried very hard, only with MinGW (cross-compilation).

The alternative is to use the TeX based hyphenator, which is very easy if you can find a patterns file that is equivalent to your libhyphen patterns file. In mod-celia we generate the libhyphen patterns file from the TeX patterns file so we are completely sure the implementations are equivalent.

**Comment by bertfrees** [comment]
@dkager: This should now have been fixed on the "libhyphen-windows" branch (depends on https://github.com/daisy/pipeline-mod-braille/issues/107).

**Comment by dkager** [comment]
This is pending the integration of both file-format and hyphenation on Windows in a single branch.

**Comment by dkager** [comment]
Think this is done.
